import { Review } from "./entities/review.entity";


// Tạo 9 review 
export const reviewList: Review[] = [
  {
    id: 1,
    teacherId: 1,
    reviewerId: 10,
    title: "Giảng dễ hiểu",
    message: "Cô Bình giảng bài rất dễ hiểu, tận tình.",
    rating: 5,
    createAt: new Date("2024-01-10"),
  },
  {
    id: 2,
    teacherId: 2,
    reviewerId: 10,
    title: "Thầy nhiệt tình",
    message: "Thầy Cường hỗ trợ học viên ngoài giờ rất nhiều.",
    rating: 4,
    createAt: new Date("2024-01-15"),
  },
  {
    id: 3,
    teacherId: 3,
    reviewerId: 10,
    title: "Bài giảng tốt",
    message: "Cô Dung soạn bài cẩn thận, kiến thức sát đề thi.",
    rating: 5,
    createAt: new Date("2024-01-20"),
  },
  {
    id: 4,
    teacherId: 4,
    reviewerId: 10,
    title: "Học vui",
    message: "Thầy Em giảng vui vẻ, dễ tiếp thu.",
    rating: 4,
    createAt: new Date("2024-01-22"),
  },
  {
    id: 5,
    teacherId: 5,
    reviewerId: 10,
    title: "Giảng hơi nhanh",
    message: "Cô Thảo giảng khá nhanh, nhưng vẫn dễ theo kịp.",
    rating: 3,
    createAt: new Date("2024-01-25"),
  },
  {
    id: 6,
    teacherId: 6,
    reviewerId: 10,
    title: "Thầy thân thiện",
    message: "Thầy Giang rất thân thiện, dễ gần.",
    rating: 5,
    createAt: new Date("2024-01-28"),
  },
  {
    id: 7,
    teacherId: 7,
    reviewerId: 10,
    title: "Ổn nhưng hơi thiếu ví dụ",
    message: "Cô Hoa dạy chắc kiến thức nhưng ví dụ hơi ít.",
    rating: 4,
    createAt: new Date("2024-02-01"),
  },
  {
    id: 8,
    teacherId: 8,
    reviewerId: 10,
    title: "Dạy kỹ",
    message: "Thầy Đạt dạy kỹ, nắm chắc kiến thức nền.",
    rating: 5,
    createAt: new Date("2024-02-05"),
  },
  {
    id: 9,
    teacherId: 9,
    reviewerId: 10,
    title: "Cô Trúc dễ thương",
    message: "Cô Trúc hỗ trợ tận tình, phong cách giảng dạy gần gũi.",
    rating: 5,
    createAt: new Date("2024-02-08"),
  },
];
